name: CI Pipeline with SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run Pytest
      run: |
        pytest

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        args: >
          -Dsonar.projectKey=ErickACL_ProyectoCriptografico
          -Dsonar.organization=erickacl
          -Dsonar.python.version=3.9
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
