name: CI Pipeline with SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest pymongo
        pip install pytest-cov

    - name: Run tests with coverage
      run: coverage run --source=main -m pytest
    
    - name: Verify coverage.xml
      run: ls -la coverage.xml

    - name: Mover archivo de cobertura
      run: mv coverage.xml ./main/

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        args: >
          -Dsonar.projectKey=ErickACL_ProyectoCriptografico
          -Dsonar.organization=erickacl
          -Dsonar.token=46967ab36f46e7617a867f58eb6603875527598d
          -Dsonar.python.version=3.9
          -Dsonar.sources=/github/workspace/main
          -Dsonar.tests=tests
          -Dsonar.python.coverage.reportPaths=main/coverage.xml
          -Dsonar.verbose=true
          -X
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}