name: CI Pipeline with SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest pymongo
        pip install pytest-cov

    - name: Run tests with coverage
      run: pytest --cov=main --cov-report=xml:coverage.xml
    
    - name: Verify coverage.xml
      run: ls -la coverage.xml

    - name: Mover archivo de cobertura
      run: mv coverage.xml ./main/

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        args: >
          -Dsonar.projectKey=ProyectoCriptografico
          -Dsonar.organization=erickacl
          -sonar.token=1ca3c64193febc3645c07d5b4bf1b6f813c27d35
          -Dsonar.python.version=3.9
          -Dsonar.sources=main
          -Dsonar.tests=tests
          -sonar.python.coverage.reportPaths=main/coverage.xml
          -Dsonar.verbose=true
          -X
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}